name: Continuos Integration Develop

on:
  pull_request:
    branches:
      ['develop', 'master']

jobs:
  ci:
    runs-on: ubuntu-latest

    setps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Rename .env.example to .env
        run: mv .env.example .env
      - name: run install, build and test
        run: |
          npm run install
          npm run build
          npm run test